// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using er_toget_forsinket_api.Repositories;

#nullable disable

namespace ertogetforsinketapi.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20251016202938_affected_stoppoint_0")]
    partial class affected_stoppoint_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("er_toget_forsinket_api.Models.TrainDelays.AffectedStopPointEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DatedVehicleJourneyRef")
                        .HasColumnType("text")
                        .HasColumnName("dated_vehicle_journey_ref");

                    b.Property<int?>("SituationExchangeId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("StopConditions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("stop_conditions");

                    b.Property<string>("StopPointRef")
                        .HasColumnType("text")
                        .HasColumnName("stop_point_ref");

                    b.HasKey("Id");

                    b.HasIndex("SituationExchangeId");

                    b.ToTable("affected_stop_point", "train_delays");
                });

            modelBuilder.Entity("er_toget_forsinket_api.Models.TrainDelays.EstimatedTimetableRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("estimated_time_table_raw", "train_delays");
                });

            modelBuilder.Entity("er_toget_forsinket_api.Models.TrainDelays.SituationExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreationTime")
                        .HasColumnType("text")
                        .HasColumnName("creation_time");

                    b.Property<string>("DescriptionNo")
                        .HasColumnType("text")
                        .HasColumnName("description_no");

                    b.Property<string>("EndTime")
                        .HasColumnType("text")
                        .HasColumnName("end_time");

                    b.Property<string>("ParticipantRef")
                        .HasColumnType("text")
                        .HasColumnName("participant_ref");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Progress")
                        .HasColumnType("text")
                        .HasColumnName("progress");

                    b.Property<string>("ReportType")
                        .HasColumnType("text")
                        .HasColumnName("report_type");

                    b.Property<string>("SituationNumber")
                        .HasColumnType("text")
                        .HasColumnName("situation_number");

                    b.Property<string>("StartTime")
                        .HasColumnType("text")
                        .HasColumnName("start_time");

                    b.Property<string>("SummaryNo")
                        .HasColumnType("text")
                        .HasColumnName("summary_no");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<string>("VersionedAtTime")
                        .HasColumnType("text")
                        .HasColumnName("versioned_at_time");

                    b.HasKey("Id");

                    b.ToTable("situation_exchange", "train_delays");
                });

            modelBuilder.Entity("er_toget_forsinket_api.Models.TrainDelays.SituationExchangeRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("situation_exchange_raw", "train_delays");
                });

            modelBuilder.Entity("er_toget_forsinket_api.Models.TrainDelays.AffectedStopPointEntry", b =>
                {
                    b.HasOne("er_toget_forsinket_api.Models.TrainDelays.SituationExchange", null)
                        .WithMany("AffectedStopPoints")
                        .HasForeignKey("SituationExchangeId");
                });

            modelBuilder.Entity("er_toget_forsinket_api.Models.TrainDelays.SituationExchange", b =>
                {
                    b.Navigation("AffectedStopPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
